# Site settings
title: A blogesque site about stuff
description: "I write about stuff like coding, physics, math and data visualization."
baseurl: ""
url: "http://maxisacson.github.io"
username: "maxisacson"

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
